### ISSUE TITLE
all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by RichardMyers** [StephanPreibisch/SeparableConvolutionCUDALib#3]
This may not be specifically a SeparableConvolutionCUDA.DLL problem, but I thought I'd share it in case someone else has had this problem and can suggest a solution.

This problem did not occur until after I upgraded to Windows 10 x64 from Windows 7 x64.  I also tried completely uninstalling and reinstalling CUDA Toolkit version 6.5, Visual Studio 2013 vc_redist and performed multiple reboots.

1) run latest Fiji
2) Multiview Reconstruction App
3) Detect Interest points (all defaults for DoG)
4) Compute on: GPU accurate (Nvidia CUDA via JNI)
5) Selected: SeparableConvolutionCUDA.dll
6) I select my Quadro K2200 card (which is also my video card)
7) Fiji crashes, debug log shows this error message before crash:

"all CUDA-capable devices are busy or unavailable in C:/Temp/CUDA/SeparableConvolutionCUDALib/SeparableConvolutionCUDALib-master/src/separableConvolution_15.cu at line 367"

I searched for tips on the internet and didn't find anything relevant.  I am using the version of SeparableConvolutionCUDA.dll from [here](https://github.com/StephanPreibisch/SeparableConvolutionCUDALib/releases).

Other NVidia CUDA diagnostics appear to work.

I will attach the result of devicequery.exe

[devicequery.txt](https://github.com/StephanPreibisch/SeparableConvolutionCUDALib/files/373159/devicequery.txt)

**Comment by StephanPreibisch** [comment]
Hi, I have not used Windows in some time but it almost sounds like it could simply be a question of re-compiling it, maybe it is due to changes in Windows 10? Would you be able to compile it under Windows?

**Comment by StephanPreibisch** [comment]
And thanks for pointing that out :)

**Comment by RichardMyers** [comment]
This appears to be an NVidia issue according to this case: [cudaMalloc error on Windows 10](https://devtalk.nvidia.com/default/topic/919583/cudamalloc-error-on-windows-10/)

I just now recompiled it on Windows 10, and with CUDA 7.5 and I get the same result - a crash.

Would you like to check in my Windows project files? I notice a pull request for CMake is also pending and that would perhaps be better.

**Comment by StephanPreibisch** [comment]
I do not have a Windows computer to really do anything about it at this point. Maybe we can just wait until Nvidia fixes the issue ... seems like this could happen as many others have the same problem? What do you think?

**Comment by RichardMyers** [comment]
I agree, no point in working on this further until we have a potential fix from NVidia.   Since it works with the CPU, we have a reasonable workaround.

**Comment by RichardMyers** [comment]
@StephanPreibisch  I tested the latest driver and can confirm that [upgrading to NVidia driver 372.70](https://devtalk.nvidia.com/default/topic/919583/cuda-programming-and-performance/cudamalloc-error-on-windows-10/2) fixes this issue.

**Comment by StephanPreibisch** [comment]
Great, thanks!

**Comment by mnqslbs2** [comment]
@RichardMyers I am trying and failing to recompiled it on Windows 10 x64 with Cuda toolkit 10 and VS2017. Would you be able to share your Windows 10 .dll and ideally the project files so I can see how you got it to work with CUDA 7.1 nad VS2013? I can compile the CUDA sample for devicequery.exe.
